FROM python:alpine3.20

WORKDIR /opt/rysen

COPY requirements.txt ./
RUN apk add --no-cache gcc musl-dev libffi-dev mariadb-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del gcc musl-dev libffi-dev mariadb-dev && \
    apk add --no-cache mariadb-connector-c

COPY hytera_proxy.py hytera_const.py ./

ENTRYPOINT ["python3", "hytera_proxy.py", "-c", "/etc/rysen/hytera-proxy.cfg"]
