voiceMap = {
   'en_GB': {
                'A': 'alpha',
                'B': 'bravo',
                'C': 'charlie',
                'D': 'delta',
                'E': 'echo',
                'F': 'foxtrot',
                'G': 'golf',
                'H': 'hotel',
                'I': 'india',
                'J': 'juliet',
                'K': 'kilo',
                'L': 'lima',
                'M': 'mike',
                'N': 'november',
                'O': 'oscar',
                'P': 'papa',
                'Q': 'quebec',
                'R': 'romeo',
                'S': 'sierra',
                'T': 'tango',
                'U': 'uniform',
                'V': 'victor',
                'W': 'whiskey',
                'X': 'x-ray',
                'Y': 'yankee',
                'Z': 'zulu',
                'to': 'silence',
                'notlinked': 'not-linked',
                'linkedto': 'linked-to'
    },

    
    'en_GB_2': {
                'A': 'alpha',
                'B': 'bravo',
                'C': 'charlie',
                'D': 'delta',
                'E': 'echo',
                'F': 'foxtrot',
                'G': 'golf',
                'H': 'hotel',
                'I': 'india',
                'J': 'juliet',
                'K': 'kilo',
                'L': 'lima',
                'M': 'mike',
                'N': 'november',
                'O': 'oscar',
                'P': 'papa',
                'Q': 'quebec',
                'R': 'romeo',
                'S': 'sierra',
                'T': 'tango',
                'U': 'uniform',
                'V': 'victor',
                'W': 'whiskey',
                'X': 'x-ray',
                'Y': 'yankee',
                'Z': 'zulu',
                'to': 'silence',
                'notlinked': 'not-linked',
                'linkedto': 'linked-to'
    },

    'en_US': {
                'to': '2',
                'freedmr': 'silence',
                'this-is': 'silence'
    },
    
    'es_ES': {
                '1': 'one',
                '2': 'two',
                '3': 'three',
                '4': 'four',
                '5': 'five',
                '6': 'six',
                '7': 'seven',
                '8': 'eight',
                '9': 'nine',
                'A': 'alfa',
                'B': 'bravo',
                'C': 'charlie',
                'D': 'delta',
                'E': 'echo',
                'F': 'foxtrot',
                'G': 'golf',
                'H': 'hotel',
                'I': 'india',
                'J': 'juliet',
                'K': 'kilo',
                'L': 'lima',
                'M': 'mike',
                'N': 'november',
                'O': 'oscar',
                'P': 'papa',
                'Q': 'quebec',
                'R': 'romeo',
                'S': 'sierra',
                'T': 'tango',
                'U': 'uniform',
                'V': 'victor',
                'W': 'whiskey',
                'X': 'x-ray',
                'Y': 'yankee',
                'Z': 'zulu',
                'to': 'silence',
                'notlinked': 'not-linked',
                'linkedto': 'linked-to'
    },
    'es_ES_2': {
                '1': 'one',
                '2': 'two',
                '3': 'three',
                '4': 'four',
                '5': 'five',
                '6': 'six',
                '7': 'seven',
                '8': 'eight',
                '9': 'nine',
                'A': 'alfa',
                'B': 'bravo',
                'C': 'charlie',
                'D': 'delta',
                'E': 'echo',
                'F': 'foxtrot',
                'G': 'golf',
                'H': 'hotel',
                'I': 'india',
                'J': 'juliet',
                'K': 'kilo',
                'L': 'lima',
                'M': 'mike',
                'N': 'november',
                'O': 'oscar',
                'P': 'papa',
                'Q': 'quebec',
                'R': 'romeo',
                'S': 'sierra',
                'T': 'tango',
                'U': 'uniform',
                'V': 'victor',
                'W': 'whiskey',
                'X': 'x-ray',
                'Y': 'yankee',
                'Z': 'zulu',
                'to': 'silence',
                'notlinked': 'not-linked',
                'linkedto': 'linked-to'
    },
    
    'fr_FR': {
                'A': 'alpha',
                'B': 'bravo',
                'C': 'charlie',
                'D': 'delta',
                'E': 'echo',
                'F': 'foxtrot',
                'G': 'golf',
                'H': 'hotel',
                'I': 'india',
                'J': 'juliet',
                'K': 'kilo',
                'L': 'lima',
                'M': 'mike',
                'N': 'november',
                'O': 'oscar',
                'P': 'papa',
                'Q': 'quebec',
                'R': 'romeo',
                'S': 'sierra',
                'T': 'tango',
                'U': 'uniform',
                'V': 'victor',
                'W': 'whiskey',
                'X': 'x-ray',
                'Y': 'yankee',
                'Z': 'zulu',
                'to': 'silence',
                'notlinked': 'not-linked',
                'linkedto': 'linked-to'
    },

   'pt_PT': {
                'A': 'alpha',
                'B': 'bravo',
                'C': 'charlie',
                'D': 'delta',
                'E': 'echo',
                'F': 'foxtrot',
                'G': 'golf',
                'H': 'hotel',
                'I': 'india',
                'J': 'juliet',
                'K': 'kilo',
                'L': 'lima',
                'M': 'mike',
                'N': 'november',
                'O': 'oscar',
                'P': 'papa',
                'Q': 'quebec',
                'R': 'romeo',
                'S': 'sierra',
                'T': 'tango',
                'U': 'uniform',
                'V': 'victor',
                'W': 'whiskey',
                'X': 'x-ray',
                'Y': 'yankee',
                'Z': 'zulu',
                'to': 'silence',
                'notlinked': 'not-linked',
                'linkedto': 'linked-to'
    },

    
    'de_DE': {
                'to': 'silence',
                'freedmr': 'silence',
                'this-is': 'silence'
    },
    
    'dk_DK': {
                'to': 'silence',
                'freedmr': 'silence',
                'this-is': 'silence'
                    
    },
    
    'it_IT': {
                'to': 'silence',
                'freedmr': 'silence',
                'this-is': 'silence'
    },
    
    'no_NO': {
                'to': 'silence',
                'freedmr': 'silence',
                'this-is': 'silence'
    },
    
    'pl_PL': {
                'to': 'silence',
                'freedmr': 'silence',
                'this-is': 'silence'
    },
    
    'se_SE': {
                'to': 'silence',
                'freedmr': 'silence',
                'this-is': 'silence'
    },
    
    'CW': {
                'to': 'silence'
    }


}
    
