###############################################################################
# Copyright (C) 2020 Simon Adlem, G7RZU <g7rzu@gb7fr.org.uk>  
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
###############################################################################

FROM python:3.7-alpine

COPY entrypoint-proxy /entrypoint

RUN adduser -D -u 54001 hbmon && \
        apk update && \
        apk add git gcc musl-dev  libffi-dev libssl-dev cargo && \
        cd /opt && \
        git clone https://github.com/sp2ong/HBMonv2.git && \
        cd /opt/HBmonv2 && \
        pip install --no-cache-dir -r requirements.txt && \
        apk del git gcc musl-dev && \
        chown -R radio: /opt/HBMonv2

USER hbmon

ENTRYPOINT [ "/entrypoint" ]
