#!/bin/bash
# RYSEN Master+ Configuration menu DO-NOT-ALTER THIS FILE!!!!!!!!!!
# SYSTEM-X FORMERLY RYSEN MASTER+ (HBlink3) A FORK OF THE FREEDMR / HBLINK PROJECT
# This script written by Shane Daley M0VUB. The script gracefully shutsdown services while services are cleaned and logs are truncated.
# We can also add items in this script for future use like updates or further log trims.
# Add to the cron tab for auto execution

#   Copyright (C) 2020 Shane P, Daley  M0VUB <support@gb7nr.co.uk>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

# Main MENU system.....
while : ; do
menuopt=$(whiptail --title "RYSEN Master+ | SYSTEM-X Control" --menu "Select option by using the up and down arrows on your keyboard. Once selected by press enter:" 23 56 13 \
1 " Restart Master " \
2 " Stop Master " \
3 " Start Master " \
4 " Hard Flush Master " \
5 " Soft Flush Master " \
6 " Edit Configuration " \
7 " Edit rules.py " \
8 " Edit Proxy Config " \
9 " Edit Dashboard Config " \
10 " Update Master Server Software " \
11 " Full Upgrade RYSEN Master+ " \
12 " Operating System update " \
13 " Reboot Entire Server " 3>&1 1>&2 2>&3)
exitstatus=$?
# Back-end rysen menu
#exitstatus=$?
if [ $exitstatus = 0 ]; then
    echo "You have chosen option:" $menuopt
else
    echo "Type 'menu' to start RYSEN Master+ SYSTEX-X Control Menu "; break;
fi
# Action
case $menuopt in
1)
/usr/local/sbin/systemx-restart ;;
2)
/usr/local/sbin/systemx-stop ;;
3)
/usr/local/sbin/systemx-start ;;
4)
/usr/local/sbin/systemx-flush ;;
5)
/usr/local/sbin/systemx-soft-flush ;;
6)
sudo nano /etc/rysen/rysen.cfg ;;
7)
sudo nano /etc/rysen/rules.py ;;
8)
sudo nano /etc/rysen/proxy.cfg ;;
9)
sudo nano /etc/rysen/fdmr-mon.cfg ;;
10)
/usr/local/sbin/systemx-update ;;
11)
echo "No updates" && sleep 2 ;;
12)
sudo apt-get update -y && sudo apt-get upgrade ;;
13)
sudo reboot now ;
esac
done
exit

# Menu system by ShaYmez https://github/ShaYmez
