#!/bin/bash
# Version 1.3.9r3
# SYSTEM-X FORMERLY RYSEN MASTER+ (HBlink3) A FORK OF THE FREEDMR / HBLINK PROJECT
# This script written by Shane Daley M0VUB. The script gracefully shutsdown services while services are cleaned and logs are truncated.
# We can also add items in this script for future use like updates or further log trims.
# Add to the cron tab for auto execution

#   Copyright (C) 2020 Shane P, Daley  M0VUB <support@gb7nr.co.uk>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

# Update containers / service clean and restart of services..

echo Restarting Master Stack.....
sleep 1
echo "."
sleep 1
echo ".."
sleep 1
echo "..."
sleep 1
echo "....."
cd /etc/rysen
docker-compose restart
sleep 1

figlet "SYSTEM-X." 
sleep 1

echo "Checking System-X is composed....."
sleep 1
docker ps
sleep 1

echo "Flushing network tracking table....."
conntrack -F
sleep 1

echo "Flushing dashboard tables"
docker exec monitor python3 mon_db.py --update

echo "Now Exiting....."
sleep 1
echo .
sleep 1
echo ..
sleep 1
echo ...
sleep 1
echo ....
echo "SYSTEM X has been restarted. Process is now complete and you may now exit. AKA ShaYmez."
