#!/bin/bash
# Version 1.3.9r3
# SYSTEM-X FORMERLY RYSEN MASTER+ (HBlink3) A FORK OF THE FREEDMR / HBLINK PROJECT
# This script written by Shane Daley M0VUB. The script gracefully shutsdown services while services are cleaned and logs are truncated.
# We can also add items in this script for future use like updates or further log trims.
# Add to the cron tab for auto execution

#   Copyright (C) 2024 Shane P, Daley  M0VUB <support@gb7nr.co.uk>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

# Start service clean/truncate/soft flush and restart of services.

echo "Stopping Master Stack....."
cd /etc/rysen
docker-compose down
echo "Done."
sleep 1

echo "System-X Flush and maintenance loop starting....."
sleep 1

echo "Starting truncate RYSEN log /var/log/rysen....."
truncate -s 0 /var/log/rysen/*log &&

#Permissions reset
chown -R 54000 /etc/rysen

#Restart all services gracefully
echo "Restart all services....."
sleep 1

echo "Starting System-X....."
docker-compose up -d

sleep 1
figlet "SYSTEM-X."
sleep 1
echo "System-X is composed....."

docker ps

echo "Checking startup error logs....."

docker container logs systemx 
echo "Done."

echo "Flushing network tracking table....."
conntrack -F
sleep 1

echo "Flushing dashboard tables"
docker exec monitor python3 mon_db.py --update

echo "Done. Now Exiting....."

echo "System-X is now online. Soft Flush is complete and you may now exit. AKA ShaYmez."
#
# This script has been developed by the one and only ShaYmez. Visit https://github/shaymez for more super scripts!
echo "All systems have been flushed/cleaned and ready to go. Aka Dr. Node. ShaYmez, System-X"
